name: GitHub CI

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Standard Checkout
        uses: actions/checkout@v4
      
      - name: Set up Java for publishing
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          server-username: g-filomena  # env variable name for username
          server-password: ${{ secrets.G_TOKEN }}
            
      - name: Publish package
        run: mvn clean deploy --settings $GITHUB_WORKSPACE/.m2/settings.xml -X
        env:
          GITHUB_USER: g-filomena
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
              